version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    cap_add:
      - NET_ADMIN
    environment:
      DB_HOST: "34.170.25.118"
      DB_PORT: "5432"
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: Q9X638hs2Y78
      RPC_URL: localhost:8233
      RPC_USERNAME: user
      RPC_PASSWORD: password
      ALLOW_MULTIPLE_THREADS: true
    ports:
      - "8232:8232"

volumes:
  postgres_data:
  zcash_data:
  zcash_params:
