# Use a base image with necessary build tools installed
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies (the list may need updates)
RUN apt-get update && apt-get install -y \
  build-essential pkg-config libc6-dev m4 g++-multilib \
  autoconf libtool ncurses-dev unzip git python3 \
  python3-zmq zlib1g-dev wget curl bsdmainutils automake

# Clone the zcashd source code from the official repository
RUN git clone https://github.com/zcash/zcash.git /zcash
WORKDIR /zcash

# Checkout the desired version
#RUN git checkout v4.5.1

# Fetch cryptographic keys
RUN ./zcutil/fetch-params.sh

# Build zcashd
RUN ./zcutil/build.sh -j$(nproc)

RUN mkdir -p /root/.zcash
COPY ./zcash-data-dir/zcash.conf /root/.zcash/zcash.conf
COPY ./zcash-data-dir/zcash.conf /zcash
COPY ./zcash-data-dir/zcash.conf /zcash/src


RUN chmod +x /zcash/src/zcash-cli
RUN mkdir -p /root/.zcash/testnet3 && chown -R root:root /root/.zcash

# Default command to run when starting the container
CMD ["/zcash/src/zcashd", "-reindex", "-printtoconsole"]
