version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    environment:
      CONFIG_PATH: "./config.yaml"

  zcash_zcashd:
    image: electriccoinco/zcashd
    user: "2001:2001" 
    volumes:
      - zcash_data:/srv/zcashd/.zcash
      - zcash_params:/srv/zcashd/.zcash-params
    environment:
      ZCASHD_NETWORK: "testnet" 
      ZCASHD_RPCPASSWORD: password
      ZCASHD_RPCUSER: user
      ZCASHD_ALLOWIP: "0.0.0.0/0"
    ports:
      - "8232:8232"
      - "8233:8233"
      - "18233:18233"
      - "18232:18232"
    cap_add:
      - NET_ADMIN
    privileged: true

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  zcash_data:
  zcash_params:
  postgres_data:
